#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "Executing 'manage.py syncdb --noinput'"
python $OPENSHIFT_REPO_DIR/wsgi/pypi/manage.py syncdb --noinput

echo "Executing 'manage.py collectstatic'"
python $OPENSHIFT_REPO_DIR/wsgi/pypi/manage.py collectstatic
