#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

source ${OPENSHIFT_HOMEDIR}python-2.6/virtenv/bin/activate
 
export PYTHON_EGG_CACHE=${OPENSHIFT_HOME_DIR}python-2.6/virtenv/lib/python2.6/site-packages
 
echo "Executing 'manage.py syncdb --noinput'"
python ${OPENSHIFT_REPO_DIR}wsgi/${OPENSHIFT_APP_NAME}/manage.py syncdb --noinput
python ${OPENSHIFT_REPO_DIR}wsgi/${OPENSHIFT_APP_NAME}/manage.py loaddata ${OPENSHIFT_REPO_DIR}wsgi/${OPENSHIFT_APP_NAME}/fixtures/initial_data.json
 
echo "Executing 'manage.py collectstatic --noinput -v0'"
python ${OPENSHIFT_REPO_DIR}wsgi/${OPENSHIFT_APP_NAME}/manage.py collectstatic --noinput -v0
