#!/usr/bin/env python

import os
import sys

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pypi.settings")
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'pypi'))

virtenv = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], 'python-2.6/virtenv')
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')

try:
    # activate virtualenv    
    activate_this = os.path.join(virtenv, 'bin', 'activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
except:
    pass

import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
